name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unit_tests:
    name: Unit Tests
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_26.0.1.app
      - name: Cache SPM
        uses: actions/cache@v3
        with:
          path: ~/Library/Developer/Xcode/DerivedData/SourcePackages
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
      - name: Set Default Scheme
        run: |
          default=BabyDashboardTestsOnCI
          echo $default | cat >default
          echo Using default scheme: $default
      - name: Test Model and Logic
        env:
          scheme: ${{ 'default' }}
          platform: ${{ 'iOS Simulator' }}
        run: |
          device=`xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//"`
          if [ $scheme = default ]; then scheme=$(cat default); fi
          if [ "`ls -A | grep -i \.xcworkspace$`" ]; then filetype_parameter="workspace" && file_to_build="`ls -A | grep -i \.xcworkspace$`"; else filetype_parameter="project" && file_to_build="`ls -A | grep -i \.xcodeproj$`"; fi
          file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`
          xcodebuild test -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -destination "platform=$platform,name=$device" -only-testing:BabyDashboardTests -only-testing:ModelTests

  ui_tests:
    name: UI Tests
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_26.0.1.app
      - name: Cache SPM
        uses: actions/cache@v3
        with:
          path: ~/Library/Developer/Xcode/DerivedData/SourcePackages
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
      - name: Set Default Scheme
        run: |
          default=BabyDashboardTestsOnCI
          echo $default | cat >default
          echo Using default scheme: $default
      - name: Test UI
        env:
          scheme: ${{ 'default' }}
          platform: ${{ 'iOS Simulator' }}
        run: |
          device=`xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//"`
          if [ $scheme = default ]; then scheme=$(cat default); fi
          if [ "`ls -A | grep -i \.xcworkspace$`" ]; then filetype_parameter="workspace" && file_to_build="`ls -A | grep -i \.xcworkspace$`"; else filetype_parameter="project" && file_to_build="`ls -A | grep -i \.xcodeproj$`"; fi
          file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`
          xcodebuild test -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -destination "platform=$platform,name=$device" -only-testing:BabyDashboardUITests -parallel-testing-enabled YES -resultBundlePath TestResults.xcresult
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: TestResults.xcresult
          path: TestResults.xcresult
